use std::sync::Arc;
use serde::{Deserialize, Serialize};

use crate::client::ClientInner;
use crate::error::Result;

/// The image format to request thumbnails in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThumbnailFormat {
    Png,
    Jpeg,
}

impl ThumbnailFormat {
    pub fn as_str(&self) -> &'static str {
        match self {
            ThumbnailFormat::Png => "Png",
            ThumbnailFormat::Jpeg => "Jpeg",
        }
    }
}

/// The return policy when a thumbnail is not yet generated.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThumbnailReturnPolicy {
    PlaceHolder,
    AutoGenerated,
    ForceAutoGenerated,
}

impl ThumbnailReturnPolicy {
    pub fn as_str(&self) -> &'static str {
        match self {
            ThumbnailReturnPolicy::PlaceHolder => "PlaceHolder",
            ThumbnailReturnPolicy::AutoGenerated => "AutoGenerated",
            ThumbnailReturnPolicy::ForceAutoGenerated => "ForceAutoGenerated",
        }
    }
}

/// The current state of a thumbnail.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
pub enum ThumbnailState {
    Completed,
    Pending,
    Blocked,
    Error,
    Unknown,
}

/// The avatar thumbnail type to request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AvatarThumbnailType {
    FullBody,
    HeadShot,
    Bust,
}

impl AvatarThumbnailType {
    pub fn as_str(&self) -> &'static str {
        match self {
            AvatarThumbnailType::FullBody => "avatar",
            AvatarThumbnailType::HeadShot => "avatar-headshot",
            AvatarThumbnailType::Bust => "avatar-bust",
        }
    }
}

/// A thumbnail result for a single item.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Thumbnail {
    pub target_id: u64,
    pub state: String,
    pub image_url: Option<String>,
    pub version: Option<String>,
}

/// Provides methods to request thumbnails from the Roblox API.
pub struct ThumbnailProvider {
    pub(crate) client: Arc<ClientInner>,
}

impl ThumbnailProvider {
    pub fn new(client: Arc<ClientInner>) -> Self {
        Self { client }
    }

    /// Fetches avatar thumbnails for a list of user IDs.
    ///
    /// - `size` — e.g. `"420x420"`, `"150x150"`, `"48x48"`, etc.
    /// - `format` — `Png` or `Jpeg`.
    /// - `is_circular` — whether to apply a circular crop.
    /// - `thumbnail_type` — which avatar thumbnail type to request.
    ///
    /// # Example
    /// ```rust,no_run
    /// # async fn example() {
    /// # use roblox::{Client, thumbnails::{AvatarThumbnailType, ThumbnailFormat}};
    /// let client = Client::new();
    /// let thumbs = client.thumbnails
    ///     .get_user_avatar_thumbnails(&[1, 2], "420x420", ThumbnailFormat::Png, false, AvatarThumbnailType::FullBody)
    ///     .await
    ///     .unwrap();
    /// for thumb in thumbs {
    ///     println!("{}: {:?}", thumb.target_id, thumb.image_url);
    /// }
    /// # }
    /// ```
    pub async fn get_user_avatar_thumbnails(
        &self,
        user_ids: &[u64],
        size: &str,
        format: ThumbnailFormat,
        is_circular: bool,
        thumbnail_type: AvatarThumbnailType,
    ) -> Result<Vec<Thumbnail>> {
        let ids: Vec<String> = user_ids.iter().map(|id| id.to_string()).collect();
        let url = self.client.url_generator.get_url(
            "thumbnails",
            &format!("v1/users/{}", thumbnail_type.as_str()),
        );
        let resp = self
            .client
            .http
            .get(&url)
            .query(&[
                ("userIds", ids.join(",")),
                ("size", size.to_string()),
                ("format", format.as_str().to_string()),
                ("isCircular", is_circular.to_string()),
            ])
            .send()
            .await?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(crate::error::RobloxError::from_status(status, &body));
        }

        let data: serde_json::Value = resp.json().await?;
        let thumbnails: Vec<Thumbnail> = serde_json::from_value(data["data"].clone())?;
        Ok(thumbnails)
    }

    /// Fetches thumbnails for a list of asset IDs.
    pub async fn get_asset_thumbnails(
        &self,
        asset_ids: &[u64],
        size: &str,
        format: ThumbnailFormat,
        is_circular: bool,
    ) -> Result<Vec<Thumbnail>> {
        let ids: Vec<String> = asset_ids.iter().map(|id| id.to_string()).collect();
        let url = self
            .client
            .url_generator
            .get_url("thumbnails", "v1/assets");
        let resp = self
            .client
            .http
            .get(&url)
            .query(&[
                ("assetIds", ids.join(",")),
                ("size", size.to_string()),
                ("format", format.as_str().to_string()),
                ("isCircular", is_circular.to_string()),
            ])
            .send()
            .await?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(crate::error::RobloxError::from_status(status, &body));
        }

        let data: serde_json::Value = resp.json().await?;
        let thumbnails: Vec<Thumbnail> = serde_json::from_value(data["data"].clone())?;
        Ok(thumbnails)
    }

    /// Fetches badge thumbnails for a list of badge IDs.
    pub async fn get_badge_thumbnails(
        &self,
        badge_ids: &[u64],
        format: ThumbnailFormat,
        is_circular: bool,
    ) -> Result<Vec<Thumbnail>> {
        let ids: Vec<String> = badge_ids.iter().map(|id| id.to_string()).collect();
        let url = self
            .client
            .url_generator
            .get_url("thumbnails", "v1/badges/icons");
        let resp = self
            .client
            .http
            .get(&url)
            .query(&[
                ("badgeIds", ids.join(",")),
                ("size", "150x150".to_string()),
                ("format", format.as_str().to_string()),
                ("isCircular", is_circular.to_string()),
            ])
            .send()
            .await?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(crate::error::RobloxError::from_status(status, &body));
        }

        let data: serde_json::Value = resp.json().await?;
        let thumbnails: Vec<Thumbnail> = serde_json::from_value(data["data"].clone())?;
        Ok(thumbnails)
    }

    /// Fetches group icon thumbnails for a list of group IDs.
    pub async fn get_group_icons(
        &self,
        group_ids: &[u64],
        size: &str,
        format: ThumbnailFormat,
        is_circular: bool,
    ) -> Result<Vec<Thumbnail>> {
        let ids: Vec<String> = group_ids.iter().map(|id| id.to_string()).collect();
        let url = self
            .client
            .url_generator
            .get_url("thumbnails", "v1/groups/icons");
        let resp = self
            .client
            .http
            .get(&url)
            .query(&[
                ("groupIds", ids.join(",")),
                ("size", size.to_string()),
                ("format", format.as_str().to_string()),
                ("isCircular", is_circular.to_string()),
            ])
            .send()
            .await?;

        if !resp.status().is_success() {
            let status = resp.status();
            let body = resp.text().await.unwrap_or_default();
            return Err(crate::error::RobloxError::from_status(status, &body));
        }

        let data: serde_json::Value = resp.json().await?;
        let thumbnails: Vec<Thumbnail> = serde_json::from_value(data["data"].clone())?;
        Ok(thumbnails)
    }
}
